[project]
name = "ads-platform-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "annotated-doc==0.0.5",
    "annotated-types==0.8.0",
    "anyio==4.14.2",
    "cffi==2.1.1",
    "click==8.4.2",
    "cryptography==50.0.0",
    "dpapick3==0.7.1",
    "enum-compat==0.0.3",
    "fastapi==0.141.1",
    "greenlet==3.5.5",
    "h11==0.16.0",
    "idna==3.19",
    "jinja2==3.1.6",
    "markupsafe==3.0.3",
    "pyasn1==0.6.4",
    "pycparser==3.0",
    "pycryptodome==3.23.0",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "python-dotenv==1.2.3",
    "python-multipart==0.0.32",
    "python-registry==1.3.1",
    "sqlalchemy==2.0.52",
    "starlette==1.6.0",
    "typing-extensions==4.16.0",
    "typing-inspection==0.4.4",
    "unicodecsv==0.14.1",
    "uvicorn==0.52.4",
]
